#  NumPy

o Numpy is an open-source library for working efficiently with arrays. 

o Important data science library in Python as many other important libraries depend on it.

o Some of Numpy's advantages:

    - Mathematical operations on NumPy’s ndarray objects are up to 50x faster than iterating over native Python lists 
    
    - Efficiency gains are due to NumPy storing array elements in an ordered single location within memory and requiring
      that all elements be the same type.
    
    - Provides indexing syntax for easily accessing portions of data within an array.
    
    - Contains built-in functions that improve quality of life when working with arrays and math, such as functions for
      linear algebra, array transformations, and matrix math.
    
    - It requires fewer lines of code for most mathematical operations than native Python lists.
    
    - An attractive (and free) alternative to MATLAB
    
### NumPy ndarrays

o The NumPy array an n-dimensional data structure and is the central object of the NumPy package.

o Table 4.1 Array creation functions
  
### Data Types for ndarrayss
  
o The data type or dtype is a special object containing the metadata the ndarray needs to interpret a chunk of memory as a
  particular type of data.
   
o Table 4.2 NumPy Data Types


In [2]:
import numpy as np
vector = np.array([1, -1, 3, 0 , 6.5])
print(vector)
print(vector.dtype)

[ 1.  -1.   3.   0.   6.5]
float64


In [3]:
matrix = np.array([[1.5, -0.1, 3], [0, -3, 6.5],[1.5, -0.1, 3], [0, -3, 6.5]])
print(matrix)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]
 [ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


In [4]:
print(matrix)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]
 [ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


In [5]:
data = [[1.5, -0.1, 3], [0, -3, 6.5]]
arr  = np.array(data)
arr

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [6]:
arr.ndim

2

In [7]:
arr.shape

(2, 3)

In [8]:
arr.dtype

dtype('float64')

### Arithmetic with NumPy Arrays

o NumPy utilizes vectorization to allow for the use of arithmetic operators to be applied to equal size arrays eliminating
  the need for iteration.

o The data type or dtype is a special object containing the metadata the ndarray needs to interpret a chunk of memory as a
  particular type of data.
  
o Table 4.2 NumPy Data Types


In [ ]:
import numpy as np
arr1 = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
arr2 = np.array([[1.5, -1, 3], [5, -3, 6.5]])
print(arr1)
print(arr2)
print (arr1 * arr2)
print (arr2 - arr1)
print (arr1 / 2)
print (arr2 ** 2)
print(arr1)
print(arr2)

### Indexing and Slicing

o NumPy utilizes vectorization to allow for the use of arithmetic operators to be applied to equal size arrays eliminating the   need for iteration.

o Basics of indexing notation

    - Uses same notation as Python list and MATLAB syntax.
    
    - Commas are used to separate axes of an array.
    
    - Colons are used designate a slice of values within the range of the array. 
    
    - Negative numbers in an index or slice mean "from the end of the array." 
    
    - Blanks before or after colons means from the beginning of the array if before the colon and to the end of the array if 
      after the colon.
      
o Boolean Indexing     

o Fancy Indexing   

In [ ]:
arr1d = np.array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr1d[7])
print(arr1d[1:6])
print(arr1d[:4])
print(arr1d[1:-1])
print(arr2d[:2])
print(arr2d)
print(arr2d[:2, 1:])
print(arr2d)

# Boolean indexing
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(names == 'Bob')
print(data)
print(data[names == 'Bob'])

# Fancy indexing
print(data[[1,5,6,2,4]])
newdata = data[[1,5,6,2,4]]
newdata

### Transposing Arrays and Swapping Axes

o Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything. 

o o Arrays have the transpose method and the special T attribute

o When doing matrix computations such as computing the inner matrix product numpy.dot can be used

o The @ infix operator is another way to do matrix multiplication

o ndarray has the method swapaxes, which takes a pair of axis numbers and switches the indicated axes to rearrange the data


In [ ]:
arr = np.arange(15).reshape((3, 5))
print(arr)
zzz = arr.T
print(arr)
print(zzz)
print(np.dot(arr.T, arr))
print(arr.T @ arr)
print(arr.swapaxes(0, 1))
print(arr)

### Pseudorandom Number Generation

o The numpy.random module supplements the built-in Python random module with functions for efficiently generating whole arrays
  of sample values from many kinds of probability distributions
  
o Python numbers are not truely random.   Can include a seed when calling the random number generator  
  
o Table 4.3 NumPy random number generator methods


In [9]:
samples = np.random.standard_normal(size=(4, 4))
print(samples)

[[-0.35648136 -1.72710038 -1.32500629 -0.51967479]
 [ 0.35970498  0.10915563 -1.36323394  0.02994254]
 [ 1.22347403  0.16520415 -1.03412901 -0.27075449]
 [-1.40629038  0.63228677  0.24138955  0.204207  ]]


In [ ]:
rng = np.random.default_rng(seed=22345)
data = rng.standard_normal((2, 3))
print(data)

### Universal Functions: Fast Element-Wise Array Functions

o A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. 
  
o Works as a fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.
  
o Many ufuncs are simple element-wise transformations, like numpy.sqrt or numpy.exp

o Table 4-4. Unary universal functions

o Table 4-5. Binary universal functions

In [ ]:
arr = np.arange(10)
print(arr)
print(np.exp(arr))
newarr = np.sqrt(arr)
print(newarr)
remainder, whole_part = np.modf(newarr)
print(whole_part)
print(remainder)

### Array-Oriented Programming with Arrays

o  NumPy arrays utilize vectorization to allow for many kinds of data processing tasks as concise array expressions that might otherwise require writing loops. 
  
o The numpy.meshgrid function takes two one-dimensional arrays and produces two two-dimensional matrices corresponding to all
  pairs of (x, y) in the two arrays.
  

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
#print(points)
xs, ys = np.meshgrid(points, points)
print(ys)

# Chapter 9 preview
z = np.sqrt(xs ** 2 + ys ** 2)
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")


### Expressing Conditional Logic as Array Operations

o The numpy.where function is a vectorized version of the ternary expression x if condition else y.


In [ ]:
xarr = np.array([1, 2, 3, 4, 5])
yarr = np.array([6, 7, 8, 9, 10])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
print(result)

### Mathematical and Statistical Methods

o Numpy provides a set of mathematical functions that compute statistics about an entire array or about the data along an 
  axis including aggregations (often called reductions) like sum, mean, and std (standard deviation)

o Table 4-5.  Basic array statistical methods

In [ ]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.mean())
print(np.mean(arr))
print(arr.sum())
print(arr.mean(axis=0))
print(arr.mean(axis=1))

### Methods for Boolean Arrays

o When given a Boolean array, the any method tests whether one or more values in an array is True

o When given a Boolean array, the all method tests whether all  values in an array is True

In [ ]:
bools = np.array([False, False, True, False])
print(bools.any())
print(bools.all())

### Sorting

o NumPy arrays can be sorted in-place with the sort method

o Like the Python list sort method, the NumPy sort method modfies the array

o NumPy ndarrays can sort rows or columns


In [ ]:
arr = np.random.randn(6)
print(arr)
arr.sort()
print(arr)
arr = np.random.randn(5, 3)
print(arr)
arr.sort(0)
print(arr)

###   Unique and Other Set Logic

o NumPy has some basic set operations for one-dimensional ndarrays.

o Table 4-6. Array set operations


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))
uni = np.union1d(names,ints)
print(uni)

### File Input and Output with Arrays

o  Similar to file processing in Python

o  Can read and write to both text and binary files

o  More common to use pandas for file input/output