# Assignment 2 - NumPy (20 points) 
## Due: 9/15/24 (10pm)

This assignment is desiged to give you some hands-on practice with NumPy.

For all problems, when asked to write a function you must include code **within the function** to check for valid input parameter values as well as code that calls the function for multipe test cases with valid **and** invalid actual parameter values.  Do **not** use exception handling (**try/except**) statements.  Do **not** use AI (chatGPT, Copilot, etc.) to write your functions.

**Make sure to add a Markdown cell after your code cell for each problem that explains your test cases and results**.

This assignment can be done individually or as a group of up to **three students**. Only one student should turn in the assignment but all students in a group should at least submit a comment indicating who was in their group and specifying who is responsible for turning in the assignment. All members of a group should be able to explain any code that has been turned in by the group.

### 1. In the code cell below, write a Python function that generates and returns a one-dimensional numPy array of odd integers starting between parameter provided lower and upper bound limits.  The function should only accept positive integer as input.   If the user calls the function with the lowerbound value first, it should create the array in ascending order.   Othewise, it should create the array in descending order.

### In Markdown cells, describe your code and explain your test case code results for multiple calls to the function with different values (both valid and invalid) for you function input.


In [40]:
import numpy as np

def generate_odd_integers(num1, num2) :

    if not isinstance(num1, int) or not isinstance(num2, int):
        return print("Invalid input, input should")  
    if num1 <= 0 or num2 <= 0:
        return print("Invalid input, input should")  
    
    if num1 < num2:
        odd_numbers = np.arange(num1, num2 + 1)
        odd_numbers = odd_numbers[odd_numbers % 2 != 0]
    else:
        odd_numbers = np.arange(num2, num1 + 1)
        odd_numbers = odd_numbers[odd_numbers % 2 != 0]
        odd_numbers = np.flip(odd_numbers)  
    
    return odd_numbers


In [41]:
# Test cases
print(generate_odd_integers(3, 15))    # Expected output: [ 3  5  7  9 11 13 15] (ascending) as num1<num2
print(generate_odd_integers(15, 3))    # Expected output: [15 13 11  9  7  5  3] (descending) as num2>num1
print(generate_odd_integers(6, 12))    # Expected output: [7 9 11] (ascending) num1 < num2
print(generate_odd_integers(12, 6))    # Expected output: [11  9  7] (descending) num2 > num1
print(generate_odd_integers(-3, 15))   # Expected output: (invalid input) because of -6
print(generate_odd_integers(3, 0))     # Expected output: (invalid input) as no odd number between them
print(generate_odd_integers(3.5, 15))  # Expected output: (invalid input, non-integer) invalid input due to 3.5
print(generate_odd_integers(3, "15"))  # Expected output: (invalid input, non-integer) invalid input as 15 is string

[ 3  5  7  9 11 13 15]
[15 13 11  9  7  5  3]
[ 7  9 11]
[11  9  7]
Invalid input, input should
None
Invalid input, input should
None
Invalid input, input should
None
Invalid input, input should
None


The function first check for type of inputs, if its not a positive integer i.e greater than zero it will retrun the invalid input message. Further functions check if num1 is greater than num2 or vice versa. Acccording creates a numpy array of odd numbers and returns it. If num1 was greater then we reverse/ flip()  the numpy array and returns it.

### 2. In the code cell below, write a Python function that generates and returns an MxN numPy array with random integer values ranging from 1 to 1000.  The function should be provided as input (parameters) with values for M that range between 1 and 4 and N that are between 1 and 6.

### In Markdown cells, describe your code and explain your test case code results for multiple calls to the function with different values (both valid and invalid) for you function input.


In [42]:
import numpy as np

def generate_random_array(num1, num2):
    if not isinstance(num1, int) or not isinstance(num2, int):
        return "invalid input"  
    
    if num1 < 1 or num1 > 4:
        return "M is  out of bond"  
    
    if num2 < 1 or num2 > 6:
        return np.array([])  
    
    random_values = np.random.randint(1, 1001, (num1, num2))
    
    return random_values

In [43]:
print(generate_random_array(2, 3))   # Should return a 2x3 array with random integers between 1 and 1000
print(generate_random_array(4, 6))   # Should return a 4x6 array with random integers between 1 and 1000
print(generate_random_array(5, 3))   # num1 out of bounds
print(generate_random_array(3, 7))   # num2 out of bounds
print(generate_random_array(0, 5))   # num1 out of bounds
print(generate_random_array(2.5, 3)) # num1 is not an integer)
print(generate_random_array(2, "5")) # num1 is not an integer)

[[893 711 203]
 [298 902 781]]
[[756 433 823 603 557 635]
 [117 600  79 126 828 319]
 [288 219 998 927 991 752]
 [891 788 642 458 104 358]]
M is  out of bond
[]
M is  out of bond
invalid input
invalid input


### 3. In the code cell below, write a Python function that takes as input (parameters) a Python dictionary and a second parameter that can be anything.   The function should then evaluate the second parameter to determine the variable's type.   It should then create a return two numPy arrays containing the keys and values from the parameter provided Python dictionary containing only the values from the orignal Python dictionary that are of the same type as the second input parameter.  The two arrays should be parallel arrays with one array contains the keys from the dictionary and the second array contains the corresponding values associated with those keys ande each key's index should have it's corresponding value at the same index in the second array.   This function need only handle the primitive data types integer, float, string, and boolean.

### In Markdown cells, describe your code and explain your test case code results for multiple calls to the function with different values (both valid and invalid) for you function input.

In [44]:
def filter_dict_by_type(dict_data, param):
    if not isinstance(dict_data, dict): 
        print( "Invalid input - argument one shloud be dict.")
        return np.array([]), np.array([])
    
    dict_keys = []
    dict_values = []
    
    param_type = type(param)
    
    for key, value in dict_data.items():
        if isinstance(value, param_type):
            dict_keys.append(key)
            dict_values.append(value)
    
    key_arr = np.array(dict_keys)
    value_arr = np.array(dict_values)
    
    return key_arr, value_arr

In [45]:

# Example usage
test_dict = {
    'a': 1, 
    'b': 2.5, 
    'c': 'Anurag', 
    'd': True, 
    'e': False, 
    'f': 3, 
    'g': 'Ambekar', 
    'h': 4.5
}

## Destructure of keys and values will only work for valid input and to make sure not to get an err I am returning empty arr for such edge cases.


# Test with integer parameter

# valid inputs will get us right output for 1st and 2nd test case - 
keys, values = filter_dict_by_type(test_dict, 5)
print("Filtered keys (int):", keys)
print("Filtered values (int):", values)

keys,values = filter_dict_by_type(test_dict, "python")
print("Filtered keys (int):", keys)
print("Filtered values (int):", values)


# Test with string parameter
#invalid input so will get error for this as w passing list on integers and gets empty array as output.
keys,values = filter_dict_by_type([1,2,3], "itc510") 
print("Filtered keys (int):", keys)
print("Filtered values (int):", values)






Filtered keys (int): ['a' 'd' 'e' 'f']
Filtered values (int): [1 1 0 3]
Filtered keys (int): ['c' 'g']
Filtered values (int): ['Anurag' 'Ambekar']
Invalid input - argument one shloud be dict.
Filtered keys (int): []
Filtered values (int): []


# Code Explanation

1. First checks for input arg1 if not dict will print invalid input and also return two empty arrays.
2. If case one is passed we check type of arg 2.
3. Then we filter the dict and try to find values in the dict where value is same type as of our paramType.
4. If we find and we just add it out empty initialised array of dict_key and dict_values respectively.
5. once itterating through dict is complete we just return these 2 arrays as output.

### 4.  In the code cell below, write a Python function that takes as input a two-dimensional _numerical_ numPy array and then computes and returns a new two-dimension numPy array containing the mean, median, standard deviation of each _row_ where he result of he three computations is placed into three additional columns so that each aggregate value computed is placed in the same row as the values used in the calculation.   In other words, the array you return should have the same number of rows as he original but with three additional columns.

### In Markdown cells, describe your code and explain your test case code results for multiple calls to the function with different values (both valid and invalid) for you function input.

In [20]:
import numpy as np

def add_stats_to_rows(arr):
   
    if not isinstance(arr, np.ndarray) or len(arr.shape) != 2:
        return "Shape of arr is not 2*2 or its not an numpy array"
    
    if not np.issubdtype(arr.dtype, np.number):
        return "values of array are not integers."
    
    #Inbuild functions of numpy library to calculate - means,medians and std_devs
    means = np.mean(arr, axis=1)
    medians = np.median(arr, axis=1)
    std_devs = np.std(arr, axis=1)
    
    stats = np.column_stack((arr, means, medians, std_devs))
    
    return stats



In [24]:
# Test cases
test_array_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

test_array_2 = np.array([
    [1.2, 3.4, 5.6],
    [7.8, 9.1, 2.2],
    [4.4, 6.6, 8.8]
])

print("Test 1:")
print(add_stats_to_rows(test_array_1))  #
#As inputs arr were valid that is 2 * 2 array of all in we get right out out put
#[[1.         2.         3.         2.         2.         0.81649658]
# [4.         5.         6.         5.         5.         0.81649658]
# [7.         8.         9.         8.         8.         0.81649658]]


print("Test 2:")
print(add_stats_to_rows(test_array_2)) 
#As both inputs arr were valid that is 2 * 2 array of all in we get right out out put
#[[1.2        3.4        5.6        3.4        3.4        1.79629248]
# [7.8        9.1        2.2        6.36666667 7.8        2.99369708]
# [4.4        6.6        8.8        6.6        6.6        1.79629248]]

test_invalid_array = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f']
])

print(add_stats_to_rows(test_invalid_array)) 
#Here we try to input invalid array of string so it will be returned from 2nd if condition, it will satisfy first one as it is array of 2*2.
# output - values of array are not integers.


print(add_stats_to_rows([1,2,3])) 
#Here we try to input invalid array of string so it will be returned from 1st if condition as its list of numbers.

print(add_stats_to_rows(np.array([1,2,3]))) 
#Here we try to input invalid array of string so it will be returned from 1st if condition as its numpy array 1D of numbers.




Test 1:
[[1.         2.         3.         2.         2.         0.81649658]
 [4.         5.         6.         5.         5.         0.81649658]
 [7.         8.         9.         8.         8.         0.81649658]]
Test 2:
[[1.2        3.4        5.6        3.4        3.4        1.79629248]
 [7.8        9.1        2.2        6.36666667 7.8        2.99369708]
 [4.4        6.6        8.8        6.6        6.6        1.79629248]]
values of array are not integers.
Shape of arr is not 2*2 or its not an numpy array
Shape of arr is not 2*2 or its not an numpy array


The following programs initially does to checks 
1. For making sure input is numpy array and its shape is 2 * 2
2. Then in 2nd check if make sure all int are present in this array
3. Then we use inbuild method of numpy for calculating mean,median, std deviation. Here axis 1 is mentioned to make sure mean,median and mode is calcualted for each row in array.
4. Once we get these value we add extra columns to our current input of 2d array in following sequence - mean(column4),median(column5) and std devidation as (column6)
